# Configuration settings

TWITTER_API_KEY: LKn2j765n1DFMaXiXdlWCfQcS
TWITTER_API_SECRET: a7HvmvnkYEkPXaKiwhyCkaUoxovFaqoIztfuBAVGY325KA8JZ3
TWITTER_ACCESS_TOKEN: 1771171108647059456-ffMKh6nNPVRhLUW0DvYzY6UCzJj5R6
TWITTER_ACCESS_TOKEN_SECRET: SX24znhEL6o6lQTI9JSqXTT36STBJXaAh7mYpEETyUrLL

REDDIT_CLIENT_ID: 2dUMIvBLxgHWnwzO6Px0Eg
REDDIT_CLIENT_SECRET: Fa9zfPPSIs_u-fllwHmUf3va4d27rg
REDDIT_USER_AGENT: Fll0yd88

FACEBOOK_ACCESS_TOKEN: EAAPaR3CM5AgBOZBh71K1aEfCtSBYnDE6jHZBwp4VpwqI5xMftZBf7Kn3TIES3AqVDvB2jbphk8Gid5p3SxFg537PD4fTcpA7ctnqXQsTXajlcQO8lX9vLTjZB549VVNl9BgZA0mUrKXyuDljQovhDo3ZB2p9S7Ua6DAqjV4ZB3sXMg5Os7S27XLU0IADnZBWchcMLK3AxcEeplCMykO31Qp1MLR8NBeqZABMlXaUs1cKd6EFFLUsjRIPujCMEVjJw
FACEBOOK_APP_ID: 1084425295946760
FACEBOOK_APP_SECRET: 88cfba53868baef58f9b0922584dff66
FACEBOOK_CLIENT_TOKEN: 6c926bc234b7e5b5d97f24b3dfb2630f

INSTAGRAM_USERNAME: hondaboi_flloyd
INSTAGRAM_PASSWORD: imaHondaboi4lyfe!

YOUTUBE_API_KEY: AIzaSyBccjjeCS2eOv1D_CSzAyGlYXpBu_hxuFc