# Configuration settings
TWITTER_API_KEY: "YOUR_TWITTER_API_KEY"
TWITTER_API_SECRET: "YOUR_TWITTER_API_SECRET"
TWITTER_ACCESS_TOKEN: "YOUR_TWITTER_ACCESS_TOKEN"
TWITTER_ACCESS_TOKEN_SECRET: "YOUR_TWITTER_ACCESS_TOKEN_SECRET"
REDDIT_CLIENT_ID: "YOUR_REDDIT_CLIENT_ID"
REDDIT_CLIENT_SECRET: "YOUR_REDDIT_CLIENT_SECRET"
REDDIT_USER_AGENT: "YOUR_REDDIT_USER_AGENT"
FACEBOOK_ACCESS_TOKEN: "YOUR_FACEBOOK_ACCESS_TOKEN"
